import { defineConfig } from 'vite';
import { resolve } from 'path';
import { readdirSync } from 'fs';

// Long-tail SEO pages are generated by scripts/gen-seo-pages.mjs — pick them up automatically.
const seoPages = readdirSync(__dirname, { withFileTypes: true })
  .filter((d) => d.isDirectory() && /^compress-to-/.test(d.name))
  .map((d) => d.name);

export default defineConfig({
  base: './',
  build: {
    target: 'es2020',
    chunkSizeWarningLimit: 1500,
    rollupOptions: {
      input: Object.fromEntries([
        ['main', resolve(__dirname, 'index.html')],
        ['merge', resolve(__dirname, 'merge/index.html')],
        ['split', resolve(__dirname, 'split/index.html')],
        ['pdf-to-jpg', resolve(__dirname, 'pdf-to-jpg/index.html')],
        ['jpg-to-pdf', resolve(__dirname, 'jpg-to-pdf/index.html')],
        ['rotate', resolve(__dirname, 'rotate/index.html')],
        ['watermark', resolve(__dirname, 'watermark/index.html')],
        ['protect', resolve(__dirname, 'protect/index.html')],
        ['page-numbers', resolve(__dirname, 'page-numbers/index.html')],
        ['organize', resolve(__dirname, 'organize/index.html')],
        ['remove-metadata', resolve(__dirname, 'remove-metadata/index.html')],
        ['what-is-pdf', resolve(__dirname, 'what-is-pdf/index.html')],
        ...seoPages.map((name) => [name, resolve(__dirname, `${name}/index.html`)]),
      ]),
    },
  },
});
